# This is a conceptual representation of a GitHub Repository Ruleset in YAML.
# GitHub rulesets are not configured by committing a file to the repository.
# They are configured via the GitHub UI (Settings > Branches > Branch protection rules) or the GitHub API.
# This file is for documentation purposes only.

name: Main Branch Protection
enforcement: active
target: branch
include:
  - main

rules:
  # Require a pull request before merging
  - type: pull_request
    parameters:
      required_approving_review_count: 1
      dismiss_stale_reviews_on_push: true
      require_code_owner_reviews: false
      required_review_thread_resolution: true

  # Require linear history
  - type: required_linear_history

  # Block force pushes
  - type: force_push
    parameters:
      blocks_bypass_actors: true

  # Restrict deletions
  - type: deletion
    parameters:
      blocks_bypass_actors: true
