name: Release Please

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write
  issues: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    outputs:
      releases_created: ${{ steps.release.outputs.releases_created }}
      tag_name: ${{ steps.release.outputs.tag_name }}
    steps:
      - name: Release Please
        id: release
        uses: googleapis/release-please-action@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          release-type: simple

  build-and-deploy:
    needs: release-please
    if: ${{ needs.release-please.outputs.releases_created }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create build directory
        run: mkdir -p build

      - name: Copy source files
        run: cp -r src/* build/

      - name: Install minification tools
        run: |
          sudo apt-get update
          sudo apt-get install -y minify

      - name: Minify HTML files
        run: |
          for file in build/*.html; do
            if [ -f "$file" ]; then
              minify -o "${file}.min" "$file"
              mv "${file}.min" "$file"
            fi
          done

      - name: Minify CSS files
        run: |
          for file in build/css/*.css; do
            if [ -f "$file" ]; then
              minify -o "${file}.min" "$file"
              mv "${file}.min" "$file"
            fi
          done

      - name: Minify JavaScript files
        run: |
          for file in build/js/*.js; do
            if [ -f "$file" ]; then
              minify -o "${file}.min" "$file"
              mv "${file}.min" "$file"
            fi
          done

      - name: Deploy to Azure Static Web Apps
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "/build"
          output_location: "/"
